import type { Locale } from './i18n'

const copy = {
  kitchen: ['Kitchen', '厨房', 'Cuisine', 'Cocina'],
  subtitle: ['Manage your food, from receipt to dinner.', '从购物小票到晚餐，在这里管理食物。', 'Gérez vos aliments, du ticket au dîner.', 'Gestiona tus alimentos, del recibo a la cena.'],
  pantryGroup: ['Pantry', '食材库存', 'Garde-manger', 'Despensa'],
  mealsGroup: ['Meals', '餐食', 'Repas', 'Comidas'],
  householdGroup: ['Household', '家庭', 'Foyer', 'Hogar'],
  settingsGroup: ['Settings & help', '设置与帮助', 'Réglages et aide', 'Ajustes y ayuda'],
  pantry: ['Open pantry', '查看库存', 'Ouvrir le garde-manger', 'Abrir despensa'],
  list: ['Filter food', '筛选食材', 'Filtrer les aliments', 'Filtrar alimentos'],
  add: ['Add food', '添加食材', 'Ajouter des aliments', 'Añadir alimentos'],
  photo: ['Scan a receipt', '扫描购物小票', 'Scanner un ticket', 'Escanear recibo'],
  ate: ['Mark eaten', '标记已吃', 'Marquer consommé', 'Marcar consumido'],
  toss: ['Mark discarded', '标记已丢弃', 'Marquer jeté', 'Marcar desechado'],
  delete: ['Remove food', '移除食材', 'Retirer un aliment', 'Eliminar alimento'],
  snooze: ['Snooze reminder', '推迟提醒', 'Reporter le rappel', 'Posponer aviso'],
  correct: ['Correct food details', '修改食材信息', 'Corriger un aliment', 'Corregir alimento'],
  stats: ['Pantry statistics', '库存统计', 'Statistiques', 'Estadísticas'],
  cook: ['Cook from pantry', '用库存食材做饭', 'Cuisiner avec le stock', 'Cocinar con la despensa'],
  plan_current: ['Current meal plan', '当前餐食计划', 'Plan de repas actuel', 'Plan de comidas actual'],
  plan: ['Create meal plan', '创建餐食计划', 'Créer un plan de repas', 'Crear plan de comidas'],
  calendar: ['Export calendar', '导出日历', 'Exporter le calendrier', 'Exportar calendario'],
  shopping: ['Shopping list', '购物清单', 'Liste de courses', 'Lista de compras'],
  favorites: ['Saved recipes', '收藏食谱', 'Recettes favorites', 'Recetas guardadas'],
  history: ['Cooking history', '做饭记录', 'Historique des repas', 'Historial de comidas'],
  prefs: ['Food preferences', '饮食偏好', 'Préférences alimentaires', 'Preferencias alimentarias'],
  household: ['Household members', '家庭成员', 'Membres du foyer', 'Miembros del hogar'],
  invite: ['Invite someone', '邀请成员', 'Inviter un membre', 'Invitar a alguien'],
  join: ['Join a household', '加入家庭', 'Rejoindre un foyer', 'Unirse a un hogar'],
  leave: ['Leave household', '离开家庭', 'Quitter le foyer', 'Salir del hogar'],
  remove: ['Remove a member', '移除成员', 'Retirer un membre', 'Eliminar miembro'],
  bind: ['Connect Telegram group', '关联 Telegram 群组', 'Lier un groupe Telegram', 'Conectar grupo de Telegram'],
  tz: ['Time zone', '时区', 'Fuseau horaire', 'Zona horaria'],
  lang: ['Language', '语言', 'Langue', 'Idioma'],
  digest_at: ['Daily reminder hour', '每日提醒时间', 'Heure du rappel quotidien', 'Hora del aviso diario'],
  llm: ['AI provider', 'AI 服务商', 'Fournisseur IA', 'Proveedor de IA'],
  quota: ['Usage & quota', '用量与配额', 'Utilisation et quota', 'Uso y cuota'],
  buy: ['Plans & top-ups', '套餐与加购', 'Offres et recharges', 'Planes y recargas'],
  billing: ['Billing details', '账单详情', 'Détails de facturation', 'Datos de facturación'],
  help: ['Help', '帮助', 'Aide', 'Ayuda'],
  start: ['Welcome & setup', '欢迎与初始化', 'Accueil et configuration', 'Bienvenida y configuración'],
  text: ['Ask your kitchen assistant', '询问厨房助手', 'Demander à votre assistant', 'Preguntar al asistente'],
  run: ['Continue', '继续', 'Continuer', 'Continuar'],
  loading: ['Working… You can keep this page open.', '处理中，请稍候…', 'En cours… Gardez cette page ouverte.', 'En curso… Puedes mantener esta página abierta.'],
  refresh: ['Refresh results', '刷新结果', 'Actualiser les résultats', 'Actualizar resultados'],
  empty: ['Choose a feature to get started. Results and next steps appear here.', '选择一项功能开始。结果和下一步操作将显示在这里。', 'Choisissez une fonction. Les résultats et les étapes suivantes apparaîtront ici.', 'Elige una función. Los resultados y próximos pasos aparecerán aquí.'],
  results: ['Your activity', '操作结果', 'Votre activité', 'Tu actividad'],
  details: ['Details', '详细信息', 'Détails', 'Detalles'],
  feature: ['What would you like to do?', '您想做什么？', 'Que souhaitez-vous faire ?', '¿Qué quieres hacer?'],
  produce: ['Produce', '果蔬', 'Fruits et légumes', 'Frutas y verduras'],
  dairy: ['Dairy', '乳制品', 'Produits laitiers', 'Lácteos'],
  meat: ['Meat', '肉类', 'Viande', 'Carne'],
  seafood: ['Seafood', '海鲜', 'Fruits de mer', 'Mariscos'],
  bakery: ['Bakery', '烘焙食品', 'Boulangerie', 'Panadería'],
  pantryCategory: ['Pantry staples', '常温食品', 'Épicerie', 'Alimentos de despensa'],
  frozen: ['Frozen', '冷冻食品', 'Surgelés', 'Congelados'],
  beverage: ['Beverages', '饮品', 'Boissons', 'Bebidas'],
  other: ['Other', '其他', 'Autres', 'Otros'],
  item: ['Food ID', '食材编号', 'Numéro de l’aliment', 'ID del alimento'],
  days: ['Days', '天数', 'Jours', 'Días'],
  member: ['Member Telegram ID', '成员 Telegram ID', 'Identifiant Telegram du membre', 'ID de Telegram del miembro'],
  code: ['Invite code', '邀请码', 'Code d’invitation', 'Código de invitación'],
  groupId: ['Group ID (you must be a group administrator)', '群组 ID（需要群组管理员权限）', 'Identifiant du groupe (administrateur requis)', 'ID del grupo (debes ser administrador)'],
  mode: ['Invite type', '邀请类型', 'Type d’invitation', 'Tipo de invitación'],
  single: ['One person', '单人', 'Une personne', 'Una persona'],
  family: ['Reusable family link', '可重复使用的家庭链接', 'Lien familial réutilisable', 'Enlace familiar reutilizable'],
  all: ['All', '全部', 'Tous', 'Todos'],
  due: ['Due this week', '本周到期', 'À consommer cette semaine', 'Vence esta semana'],
  expired: ['Expired', '已过期', 'Périmés', 'Caducados'],
  filter: ['Filter', '筛选', 'Filtre', 'Filtro'],
  optional: ['Optional', '可选', 'Facultatif', 'Opcional'],
  receiptHint: ['Choose a JPEG or PNG photo, up to 10 MB.', '请选择 JPEG 或 PNG 照片，最大 10 MB。', 'Choisissez une photo JPEG ou PNG, 10 Mo maximum.', 'Elige una foto JPEG o PNG, máximo 10 MB.'],
  addHint: ['Describe the foods, quantities, and expiry dates. Review before adding.', '描述食材、数量和到期日，确认后添加。', 'Décrivez aliments, quantités et dates. Vérifiez avant d’ajouter.', 'Describe alimentos, cantidades y fechas. Revisa antes de añadir.'],
  prefsHint: ['Describe your diet, exclusions, favorite cuisines, or cooking time. Leave blank to view.', '描述饮食、忌口、偏好菜系或烹饪时间。留空查看。', 'Décrivez régime, exclusions, cuisines ou durée. Laissez vide pour consulter.', 'Describe dieta, exclusiones, cocinas o tiempo. Deja vacío para consultar.'],
  confirm: ['Confirm this change?', '确认此更改？', 'Confirmer cette modification ?', '¿Confirmar este cambio?'],
  confirmHint: ['This changes your food or household. Check the selection before continuing.', '此操作将更改食材或家庭，请先核对。', 'Cela modifie vos aliments ou votre foyer. Vérifiez avant de continuer.', 'Esto cambia tus alimentos o tu hogar. Comprueba antes de continuar.'],
  cancel: ['Cancel', '取消', 'Annuler', 'Cancelar'],
  reply: ['Describe the correction', '描述需要修改的信息', 'Décrivez la correction', 'Describe la corrección'],
  download: ['Download calendar', '下载日历', 'Télécharger le calendrier', 'Descargar calendario'],
  error: ['Could not connect. Refresh to check whether your action completed before trying again.', '无法连接。重试前请刷新，确认操作是否已完成。', 'Connexion impossible. Actualisez pour vérifier le résultat avant de réessayer.', 'No se pudo conectar. Actualiza para comprobar el resultado antes de reintentar.'],
  access: ['Access could not be verified. Reopen the app from Telegram and check your household membership.', '无法验证访问权限。请从 Telegram 重新打开应用，并确认家庭成员身份。', 'Accès non vérifié. Rouvrez l’application depuis Telegram et vérifiez votre adhésion au foyer.', 'No se pudo verificar el acceso. Abre la aplicación desde Telegram y comprueba tu membresía.'],
  onboarding: ['Start your kitchen or join with an invitation.', '创建厨房，或使用邀请码加入家庭。', 'Créez votre cuisine ou rejoignez un foyer avec une invitation.', 'Crea tu cocina o únete con una invitación.'],
} as const

export type WorkspaceKey = keyof typeof copy
export function w(locale: Locale, key: WorkspaceKey): string {
  return copy[key][(['en', 'zh', 'fr', 'es'] as const).indexOf(locale)]
}
